all:
  hosts:
    ecs-instance-1:
      ansible_host: <server-public-ip>
      ansible_user: <username-to-access>
      ansible_ssh_private_key_file: <path/to/privatekey>
    ecs-instance-2:
      ansible_host: <server-public-ip>
      ansible_user: <username-to-access>
      ansible_ssh_private_key_file: <path/to/privatekey>